InternalClassType: Variable
Comment: "Attention: only used when using rules!!!"
Coordinate3D: [33.300000000000004,-11.100000000000001,0]
DataType: boolean
Font: 2
HasInitValue: false
Name: RescaleExitApplication
Origin: 5e17756d-7407-4e64-9e2b-48013727ec26
ShowDataType: false
UUID: 98da3ec2-693b-4e28-9360-ca0bd900b00a
Value: false
